### ISSUE TITLE
Make chip architecture a configurable thing

### ISSUE THREAD

**Issue by bacongobbler** [jakepearson/h#2]
While I don't have any amd64 machines myself (other than Pis), a great enhancement would be to allow detection of the computer architecture to ensure `h` can be run from any machine that supports bash.

Helm's `get` script has a few tricks up its sleeve if you want to use that for detection: https://github.com/helm/helm/blob/33338eab17c1fe966f95889dde8f40696cb388a3/scripts/get#L26-L49

I'm assuming this might also be useful for https://github.com/jakepearson/k as well.

**Comment by jakepearson** [comment]
Great Idea. Fixed. Thanks @bacongobbler
